version: "3.9"

services:
  web-rr:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./rentrestful:/rentrestful
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db_1
    env_file:
      - ./.env

  db_1:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
volumes:
  postgres_data:
